# Generated by Django 3.2.2 on 2021-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_features_product_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
