# Generated by Django 3.2.2 on 2021-07-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210705_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='iconType',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='iconType',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
